# ESTRUCTURAS DE CONTROL CONDICIONALES
# if [CUALQUIER "COSA" QUE RETORNE UN VALOR DE VERDAD]:

n = int(input("INGRESE UN VALOR NUMERICO:\t"))

#CONDiCIONAL SIMPLE
if n > 10:
	print("USTED INGRESO UN NUMERO MAS GRANDE QUE 10")



#CONDICIONAL ALTERNATIVO
if n > 10:
	print("USTED INGRESO UN NUMERO MAS GRANDE QUE 10")
else:
	print("USTED INGRESO UN NUMERO MAS CHICO QUE 10")


#CONDICIONAL MULTIPLE
if n > 10:
	print("USTED INGRESO UN NUMERO MAS GRANDE QUE 10")
elif n > 5:
	print("USTED INGRESO UN NUMERO MAS GRANDE QUE 5 y mas chico que 10")
elif n > 2:
	print("USTED INGRESO UN NUMERO MAS GRANDE QUE 2 y mas chico que 5")
else:
	print("USTED INGRESO UN NUMERO MAS MAS CHICO que 2")


#CONDICIONALES ANIDADOS
if n > 10:
	print("USTED INGRESO UN NUMERO MAS GRANDE QUE 10")
else:
	if n > 5:
		print("USTED INGRESO UN NUMERO MAS GRANDE QUE 5 y mas chico que 10")
	else:
		if n > 2:
			print("USTED INGRESO UN NUMERO MAS GRANDE QUE 2 y mas chico que 5")
		else:
			print("USTED INGRESO UN NUMERO MAS MAS CHICO que 2")